# Setup
title:        Alta Cumbia
tagline:      A ball for the Amazon !
baseurl:      "https://altacumbia.github.io/"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       gfraga
  url:        http://gorka.science

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown